### ISSUE TITLE
App Store release broken

### ISSUE THREAD

**Issue by grawlinson** [bitwarden/browser#1866]
```
Uncaught Exception:
Error: dlopen(/Applications/Bitwarden.app/Contents/Resources/app-arm64.asar.unpacked/node_modules/keytar/build/Release/keytar.node, 1): no suitable image found.  Did find:
/Applications/Bitwarden.app/Contents/Resources/app-arm64.asar.unpacked/node_modules/keytar/build/Release/keytar.node: mach-o, but wrong architecture
/Applications/Bitwarden.app/Contents/Resources/app-arm64.asar.unpacked/node_modules/keytar/build/Release/keytar.node: mach-o, but wrong architecture
at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/Applications/Bitwarden.app/Contents/Resources/app-arm64.asar/node_modules/keytar/lib/keytar.js:1:14)
at Module._compile (internal/modules/cjs/loader.js:1152:30)
```

**Comment by sedony23** [comment]
Same for me on a Apple Silicon Mac. Running it in Rosetta solved it for me...
