### ISSUE TITLE
Hotkey doesn't work

### ISSUE THREAD

**Issue by KristerV** [bitwarden/browser#54]
Hey. It's strange, cuz ctrl+shift+y worked fine until I clicked the "update extensions now" button. Arch Linux, Chromium. Did not notice if it actually updated or what's going on. Here are the errors i've been able to pick up. All other functions seem to work fine.

![image](https://cloud.githubusercontent.com/assets/2750622/20744877/04a3d16e-b6e7-11e6-99a6-c58b84c02093.png)

And errors from the console (extension console as I understand):

![image](https://cloud.githubusercontent.com/assets/2750622/20744916/3e582eaa-b6e7-11e6-9805-d2107a890373.png)

same in text format, if someone's googling this:

```
_generated_background_page.html:1 Unchecked runtime.lastError while running contextMenus.create: Cannot create item with duplicate id autofill_noop
    at loadContextMenuOptions (chrome-extension://nngceckbapebfimnlniiiahkandclblb/background.js:359:29)
    at loadNoSitesContextMenuOptions (chrome-extension://nngceckbapebfimnlniiiahkandclblb/background.js:354:5)
    at chrome-extension://nngceckbapebfimnlniiiahkandclblb/background.js:216:9
    at _rejected (chrome-extension://nngceckbapebfimnlniiiahkandclblb/lib/q/q.js:844:24)
    at chrome-extension://nngceckbapebfimnlniiiahkandclblb/lib/q/q.js:870:30
_generated_background_page.html:1 Unchecked runtime.lastError while running contextMenus.create: Cannot create item with duplicate id copy-username_noop
    at loadContextMenuOptions (chrome-extension://nngceckbapebfimnlniiiahkandclblb/background.js:369:29)
    at loadNoSitesContextMenuOptions (chrome-extension://nngceckbapebfimnlniiiahkandclblb/background.js:354:5)
    at chrome-extension://nngceckbapebfimnlniiiahkandclblb/background.js:216:9
    at _rejected (chrome-extension://nngceckbapebfimnlniiiahkandclblb/lib/q/q.js:844:24)
    at chrome-extension://nngceckbapebfimnlniiiahkandclblb/lib/q/q.js:870:30
_generated_background_page.html:1 Unchecked runtime.lastError while running contextMenus.create: Cannot create item with duplicate id copy-password_noop
    at loadContextMenuOptions (chrome-extension://nngceckbapebfimnlniiiahkandclblb/background.js:379:29)
    at loadNoSitesContextMenuOptions (chrome-extension://nngceckbapebfimnlniiiahkandclblb/background.js:354:5)
    at chrome-extension://nngceckbapebfimnlniiiahkandclblb/background.js:216:9
    at _rejected (chrome-extension://nngceckbapebfimnlniiiahkandclblb/lib/q/q.js:844:24)
    at chrome-extension://nngceckbapebfimnlniiiahkandclblb/lib/q/q.js:870:30
```

**Comment by kspearrin** [comment]
The error you posted is a known issue and should not have any effect on the hot keys working. Check your chrome extension hotkey settings in Settings > Extensions (scroll down) > Keyboard Shortcuts to see if it got lost somehow.

**Comment by KristerV** [comment]
omg it's true. there isn't a hotkey there anymore.. works now, thanks.
